appApi/MyApi/urls.py
from django.urls import path
from .views import *

app_name="MyApi"

urlpatterns = [
path("",ListApi.as_view()),   
path("details/<pk>/",DetailApi.as_view(),name="posts"),
# path("user/details/<username>/",UserDetailApi.as_view(),name="user"),


]

appApi/appApi/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("updates.urls",namespace="home")),
    path("api/",include("MyApi.urls",namespace="api")),
    path("accounts/",include("accounts.urls",namespace="account")),
]

appApi/updates/urls.py
from django.urls import path
from . import views
from .views import *
app_name="updates"

urlpatterns = [
    # path('updates/',JsonCbv2.as_view(),name="update"),
    # path('', JoinFormView.as_view()),
    path('',views.JoinFormView,name="ajax"),

]

appApi/updates/models.py
import json
from django.conf import settings 
from django.db import models
from django.core.serializers import serialize
# Create your models here.


def upload(instance,filename):
    return (f"api/updates/{instance.user}/{filename}")

class Update(models.Model):
    user= models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    content = models.TextField()
    image =models.ImageField(upload_to="upload",blank=True,null=True)
    updated=models.DateTimeField(auto_now=True)
    timestamp=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

    # def serialize(self):
    #     json_data=serialize("json",[self])
    #     stuct=json.loads(json_data)
    #     data=json.dumps(stuct[0]["fields"])
    #     return data

    #another way 
    def serialize(self):
        data={
            "user":self.user.id,
            "user_name":self.user.username,
            "content":self.content,
            "image":self.image.url
            }
        data=json.dumps(data)
        return data

appApi/updates/forms.py
# yourapp.forms.py
from django import forms

class JoinForm(forms.Form): # or forms.ModelForm
    image = forms.ImageField()
    name = forms.CharField(max_length=120)
    description=forms.CharField(widget=forms.TextInput())

appApi/updates/api/views.py
from updates.models import * 



# Creating,Retrieving,Updating,Deleting
class UpdateModelDetailApi():   #this is for specific post
    def get(self,request,*args,**kwargs):
        return 
    def post(self,request,*args,**kwargs):
        return 
    def put(self,request,*args,**kwargs):
        return
    def delete(self,request,*args,**kwargs):
        return

 

class UpdateModelListApi():   #this is for all posts
    def get(self,request,*args,**kwargs):
        return 
 

appApi/updates/views.py
from django.shortcuts import render
from django.core.serializers import serialize
from django.views.generic import View
from django.http import JsonResponse,HttpResponse
from .models import *
from .mixins import JsonResponseMixin,CSRFexempt,AjaxFormMixin
from django.views.decorators.csrf import csrf_exempt
# Create your views here.


# def detail(request):
#     # URI -- uniform resorces identifier REST Api
#     data={
#         "user":100,
#         "content":100,
#         "timestamp":100,
#     }
#     return JsonResponse(data)

#     # same with CBV
# class JsonCbv1(JsonResponseMixin,CSRFexempt,View):
#     def get(self,request,*args,**kwargs):
#         # obj=Update.objects.get(id=1)
#         obj=Update.objects.all().serialize()
#         return HttpResponse(obj,content_type="application/json")


# class JsonCbv2(JsonResponseMixin,CSRFexempt,View):
#     def get(self,request,*args,**kwargs):
#         obj=Update.objects.get(id=1).serialize()
#         return HttpResponse(obj,content_type="application/json")




# yourapp.views.py

from django.views.generic import FormView

from .forms import JoinForm


# from step 2

from django.http import JsonResponse

# class JoinFormView(AjaxFormMixin,FormView):
#     form_class = JoinForm
#     template_name  = 'ajax.html'
#     success_url="/success/"
#     def form_invalid(self, form):
#         response = super(JoinFormView, self).form_invalid(form)
#         if self.request.is_ajax():
#             print("Failed")
#             return JsonResponse(form.errors, status=400)
#         else:
#             return response

#     def form_valid(self, form):
#         response = super(JoinFormView, self).form_valid(form)
#         if self.request.is_ajax():
#             print(form.cleaned_data)
#             data = {
#                 'message': "Successfully submitted form data."
#             }
#             return JsonResponse(data)
#         else:
#             return response

def JoinFormView(request):
    form=JoinForm(request.POST or None,request.FILES or None)
    if request.is_ajax():
        Update.objects.create(user=request.user,content="asdasd")
        data = {
                'message': "Successfully submitted form data."
        }
        return JsonResponse(data)
    context={"form":form}
    return render(request,"ajax.html",context)

appApi/updates/templates/ajax.html
{% extends "base.html" %}


{% block content %}
<div class="mt-3">
    <div id="alert-box"></div>
    <div id="img-box"></div>
    <form id="p-form" autocomplete="off">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Send</button>
    </form>
</div>
{% endblock content %}

appApi/updates/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Base Template</title>
  </head>
  <body>
    <div>
    {% block content %}{% endblock content %}
    </div>

    <!-- jQuery (required for this Ajax tutorial) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

<!-- start ajax 1 -->
    <!-- <script>

      // using jQuery
function getCookie(name) {
  var cookieValue = null;
  if (document.cookie && document.cookie !== '') {
      var cookies = document.cookie.split(';');
      for (var i = 0; i < cookies.length; i++) {
          var cookie = jQuery.trim(cookies[i]);
          // Does this cookie string begin with the name we want?
          if (cookie.substring(0, name.length + 1) === (name + '=')) {
              cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
              break;
          }
      }
  }
  return cookieValue;
}

var csrftoken = getCookie('csrftoken');

function csrfSafeMethod(method) {
  // these HTTP methods do not require CSRF protection
  return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
  beforeSend: function(xhr, settings) {
      if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
      }
  }
});
      $(document).ready(function(){
          var $myForm = $('.my-ajax-form')
          $myForm.submit(function(event){
              event.preventDefault()
              var $formData = $(this).serialize()
              var $thisURL = $myForm.attr('data-url') || window.location.href // or set your own url
              $.ajax({
                  method: "POST",
                  url: $thisURL,
                  data: $formData,
                  success: handleFormSuccess,
                  error: handleFormError,
              })
          })
      
          function handleFormSuccess(data, textStatus, jqXHR){
              console.log(data)
              console.log(textStatus)
              console.log(jqXHR)
              $myForm.reset(); // reset form data
          }
      
          function handleFormError(jqXHR, textStatus, errorThrown){
              console.log(jqXHR)
              console.log(textStatus)
              console.log(errorThrown)
          }
      })
      </script> -->
<!-- end ajax 1 -->
      
<script>
  const alertBox = document.getElementById('alert-box')
const imgBox = document.getElementById('img-box')
const form = document.getElementById('p-form')

const name = document.getElementById('id_name')
const description = document.getElementById('id_description')
const image = document.getElementById('id_image')

const csrf = document.getElementsByName('csrfmiddlewaretoken')
console.log(csrf)

const url = "{% url 'home:ajax' %}"

const handleAlerts = (type, text) =>{
    alertBox.innerHTML = `<div class="alert alert-${type}" role="alert">
                            ${text}
                        </div>`
}

image.addEventListener('change', ()=>{
    const img_data = image.files[0]
    const url = URL.createObjectURL(img_data)
    console.log(url)
    imgBox.innerHTML = `<img src="${url}" width="100%">`
})

form.addEventListener('submit', e=>{
    e.preventDefault()

    const fd = new FormData()
    fd.append('csrfmiddlewaretoken', csrf[0].value)
    fd.append('name', name.value)
    fd.append('description', description.value)
    fd.append('image', image.files[0])

    $.ajax({
        type: 'POST',
        url: url,
        enctype: 'multipart/form-data',
        data: fd,
        success: function(response){
            console.log(response)
            const sText = `successfully saved ${response.name}`
            handleAlerts('success', sText)
            setTimeout(()=>{
                alertBox.innerHTML = ""
                imgBox.innerHTML = ""
                name.value = ""
                description.value = ""
                image.value = ""
            }, 3000)
        },
        error: function(error){
            console.log(error)
            handleAlerts('danger', 'ups..something went wrong')
        },
        cache: false,
        contentType: false,
        processData: false,
    })
})

console.log(form)
</script>
  </body>
</html>